# domain -> 대표 담보 우선순위
# 각 계열 내에서 대표 담보로 선택될 때의 우선순위 (앞에 있을수록 높은 우선순위)

CANCER:
  - A4209       # 암진단비 (메인)
  - A4200_1     # 암진단비(유사암 제외)
  - A4299_1     # 암진단비(유사암 제외) 변형
  - A4210       # 유사암진단비
  - A4302       # 재진단암진단비
  - A9630_1     # 다빈치로봇암수술비
  - A5200       # 암수술비(유사암 제외)

CARDIO:
  - A4103       # 뇌졸중진단비
  - A4102       # 뇌출혈진단비
  - A4101       # 뇌혈관질환진단비
  - A4104_1     # 심장질환진단비
  - A4105       # 허혈성심장질환진단비
  - A5104_1     # 뇌혈관질환수술비
  - A5107_1     # 허혈성심장질환수술비

INJURY:
  - A3300_1     # 상해후유장해
  - A3100       # 골절진단비
  - A3200       # 화상진단비

SURGERY:
  - A5100       # 질병수술비
  - A5300       # 상해수술비
